# Generated by Django 4.2.11 on 2024-03-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0002_itemdetails_nameproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetailsgifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduct', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=150)),
                ('image1', models.CharField(max_length=150)),
                ('image2', models.CharField(max_length=150)),
                ('image3', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('qty', models.IntegerField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('itemsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.items')),
            ],
        ),
    ]
