# Generated by Django 4.2.11 on 2024-03-04 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='nameproduct',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
