# Generated by Django 4.2.11 on 2024-03-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
