# Generated by Django 4.2.11 on 2024-03-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('invoice_number', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
    ]
