# Generated by Django 4.2.11 on 2024-03-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='name_product',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
