# Generated by Django 4.2.11 on 2024-03-10 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_cart_name_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.order'),
        ),
    ]
